petstagram/petstagram/main/urls.py
from django.urls import path

from petstagram.main.views.generic import display_home, display_dashboard
from petstagram.main.views.pet_photos import display_photo_details, like_photo, create_pet_photo, edit_pet_photo
from petstagram.main.views.pets import create_pet, edit_pet, delete_pet
from petstagram.main.views.profiles import display_profile_details, create_profile, edit_profile, delete_profile

urlpatterns = (
    path('', display_home, name='index'),
    path('dashboard/', display_dashboard, name='dashboard'),

    path('profile/', display_profile_details, name='profile'),
    path('profile/create/', create_profile, name='create profile'),
    path('profile/edit/', edit_profile, name='edit profile'),
    path('profile/delete/', delete_profile, name='delete profile'),

    path('pet/add/', create_pet, name='create pet'),
    path('pet/edit/<int:pk>/', edit_pet, name='edit pet'),
    path('pet/delete/<int:pk>/', delete_pet, name='delete pet'),

    path('photo/details/<int:pk>/', display_photo_details, name='photo'),
    path('photo/like/<int:pk>/', like_photo, name='like photo'),
    path('photo/add/', create_pet_photo, name='create pet photo'),
    path('photo/edit/<int:pk>/', edit_pet_photo, name='edit pet photo'),
)

petstagram/petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.main.urls')),
]

petstagram/petstagram/main/models.py
import datetime

from django.db import models


class Profile(models.Model):

    FIRST_NAME_MIN_LENGTH = 2
    FIRST_NAME_MAX_LENGTH = 30
    LAST_NAME_MIN_LENGTH = 2
    LAST_NAME_MAX_LENGTH = 30

    MALE = 'Male'
    FEMALE = 'Female'
    DO_NOT_SHOW = 'Do not show'

    GENDERS = [(x, x) for x in (MALE, FEMALE, DO_NOT_SHOW)]

    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH,
    )

    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH,
    )

    profile_picture = models.URLField(
        null=True,
        blank=True,
    )

    date_of_birth = models.DateField(
        null=True,
        blank=True,
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    email = models.EmailField(
        null=True,
        blank=True,
    )

    gender = models.CharField(
        max_length=max(len(val) for val, _ in GENDERS),
        choices=GENDERS,
        default=DO_NOT_SHOW
    )

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Pet(models.Model):

    CAT = 'Cat'
    DOG = 'Dog'
    BUNNY = 'Bunny'
    PARROT = 'Parrot'
    FISH = 'Fish'
    OTHER = 'Other'

    TYPE = [(x, x) for x in (CAT, DOG, BUNNY, PARROT, FISH, OTHER)]

    name = models.CharField(
        max_length=30,
    )

    type = models.CharField(
        max_length=max(len(val) for val, _ in TYPE),
        choices=TYPE,
    )

    date_of_birth = models.DateField(
        null=True,
        blank=True,
    )

    user_profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    @property
    def age(self):
        return datetime.datetime.now().year - self.date_of_birth.year

    class Meta:
        unique_together = ('user_profile', 'name')

    def __str__(self):
        return f'{self.type}: {self.name}'


class PetPhoto(models.Model):

    photo = models.ImageField()

    tagged_animals = models.ManyToManyField(
        Pet,
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    publication_date = models.DateTimeField(
        auto_now_add=True,
    )

    likes = models.IntegerField(
        default=0,
    )

petstagram/petstagram/main/forms.py
from datetime import date

from django import forms

from petstagram.main.helpers import BootstrapFormMixin, DisabledFieldsFormMixin
from petstagram.main.models import Profile, PetPhoto, Pet
from petstagram.main.validators import MaxDateValidator


class CreateProfileForm(BootstrapFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'profile_picture')
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter first name',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter last name',
                }
            ),
            'profile_picture': forms.TextInput(
                attrs={
                    'placeholder': 'Enter URL',
                }
            ),
        }


class EditProfileForm(BootstrapFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()

    class Meta:
        model = Profile
        fields = '__all__'
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter first name',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter last name',
                }
            ),
            'profile_picture': forms.TextInput(
                attrs={
                    'placeholder': 'Enter URL',
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Enter email',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'placeholder': 'Enter description',
                    'rows': 3,
                }
            ),
            'date_of_birth': forms.DateInput(
                attrs={
                    'min': '1920-01-01',
                }
            ),
        }


class DeleteProfileForm(forms.ModelForm):
    def save(self, commit=True):
        pets = list(self.instance.pet_set.all())
        PetPhoto.objects.filter(tagged_animals__in=pets).delete()
        self.instance.delete()

        return self.instance

    class Meta:
        model = Profile
        fields = ()


class CreatePetForm(BootstrapFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()

    class Meta:
        model = Pet
        fields = ('name', 'type', 'date_of_birth')
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Enter pet name',
                }
            ),
        }


class EditPetForm(BootstrapFormMixin, forms.ModelForm):
    MIN_DATE_OF_BIRTH = date(1920, 1, 1)
    MAX_DATE_OF_BIRTH = date.today()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()

    def clean_date_of_birth(self):
        MaxDateValidator(date.today())(self.cleaned_data['date_of_birth'])
        return self.cleaned_data['date_of_birth']

    class Meta:
        model = Pet
        exclude = ('user_profile',)


class DeletePetForm(BootstrapFormMixin, DisabledFieldsFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()
        self._init_disabled_fields()

    def save(self, commit=True):
        self.instance.delete()
        return self.instance

    class Meta:
        model = Pet
        exclude = ('user_profile',)

petstagram/petstagram/main/views/generic.py
from django.shortcuts import render

from petstagram.main.models import PetPhoto
from petstagram.main.helpers import get_profile


def display_home(request):
    context = {
        'hide_nav_items': True,
    }
    return render(request, 'home_page.html', context)


def display_dashboard(request):
    profile = get_profile()
    pet_photos = PetPhoto.objects \
        .prefetch_related('tagged_animals') \
        .filter(tagged_animals__user_profile=profile) \
        .distinct()

    context = {
        'pet_photos': pet_photos
    }

    return render(request, 'dashboard.html', context)

petstagram/petstagram/main/views/pet_photos.py
from django.shortcuts import render, redirect

from petstagram.main.models import PetPhoto


def display_photo_details(request, pk):
    pet_photo = PetPhoto.objects\
        .prefetch_related('tagged_animals')\
        .get(pk=pk)

    context = {
        'pet_photo': pet_photo,
    }
    return render(request, 'photo_details.html', context)


def like_photo(request, pk):
    pet_photo = PetPhoto.objects.get(pk=pk)
    pet_photo.likes += 1
    pet_photo.save()
    return redirect('photo', pk)


def create_pet_photo(request):
    return render(request, 'photo_create.html')


def edit_pet_photo(request):
    return render(request, 'photo_edit.html')

petstagram/petstagram/main/views/pets.py
from django.shortcuts import render, redirect

from petstagram.main.forms import CreatePetForm, EditPetForm, DeletePetForm
from petstagram.main.helpers import get_profile
from petstagram.main.models import Pet


def pet_action(request, form_class, success_url, instance, template_name):
    if request.method == 'POST':
        form = form_class(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(success_url)
    else:
        form = form_class(instance=instance)

    context = {
        'form': form,
        'pet': instance,
    }

    return render(request, template_name, context)


def create_pet(request):
    return pet_action(request, CreatePetForm, 'profile', Pet(user_profile=get_profile()), 'pet_create.html')


def edit_pet(request, pk):
    return pet_action(request, EditPetForm, 'profile', Pet.objects.get(pk=pk), 'pet_edit.html')


def delete_pet(request, pk):
    return pet_action(request, DeletePetForm, 'profile', Pet.objects.get(pk=pk), 'pet_delete.html')

petstagram/petstagram/main/views/profiles.py
from django.shortcuts import render, redirect

from petstagram.main.forms import CreateProfileForm, EditProfileForm, DeleteProfileForm
from petstagram.main.models import PetPhoto, Profile, Pet
from petstagram.main.helpers import get_profile


def display_profile_details(request):
    profile = get_profile()
    pets = list(Pet.objects.filter(user_profile=profile))
    pet_photos = PetPhoto.objects\
        .filter(tagged_animals__user_profile=profile)\
        .distinct()

    total_user_likes = sum(pp.likes for pp in pet_photos)
    total_user_pets_photos = len(pet_photos)

    context = {
        'profile': profile,
        'total_user_likes': total_user_likes,
        'total_user_pets_photos': total_user_pets_photos,
        'pets': pets
    }
    return render(request, 'profile_details.html', context)


def profile_action(request, form_class, success_url, instance, template_name):
    if request.method == 'POST':
        form = form_class(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(success_url)
    else:
        form = form_class(instance=instance)

    context = {
        'form': form,
    }

    return render(request, template_name, context)


def create_profile(request):
    return profile_action(request, CreateProfileForm, 'index', Profile(), 'profile_create.html')


def edit_profile(request):
    return profile_action(request, EditProfileForm, 'profile details', get_profile(), 'profile_edit.html')


def delete_profile(request):
    return profile_action(request, DeleteProfileForm, 'index', get_profile(), 'profile_delete.html')

petstagram/petstagram/main/templates/401_error.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<div class="container mb-5 mt-2">
    <div class="jumbotron">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="position-sticky">
            <h1 class="display-4">401 Unauthorized</h1>
            <p class="lead">You should create a profile to open this page!</p>
            <hr class="my-4">
            <div class="row col-lg-6">

                <!-- Button to show when profile is NOT created -->
                <a href="#" class="btn btn-lg btn-secondary">Create Profile</a>
            </div>
        </div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</body>
</html>

petstagram/petstagram/main/templates/home_page.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron parent">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="absolute">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="inner cover">
                <h1 class="cover-heading"></h1>
                <div class="row">

                    <!-- Button to show if profile created -->
                    <div class="col-lg-6">
                        <p class="lead">
                            {% if hp %}
                                <a href="{% url 'dashboard' %}" class="btn btn-lg btn-secondary">Enter</a>
                            {% else %}
                                <a href="{% url 'create profile' %}" class="btn btn-lg btn-secondary">Create Profile</a>
                            {% endif %}
                        </p>
                    </div>

                </div>

            </div>
        </div>
    </div>

{% endblock %}

petstagram/petstagram/main/templates/pet_create-old.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <!-- Form for Adding Pet -->
            <form method="post" action="profile_details.html">
                <div class="form-group">
                    <label for="name">Pet Name</label>
                    <input type="text" class="form-control" name="first_name" placeholder="Enter name"
                           id="name"/>
                </div>
                <div class="form-group">
                    <label for="type_animal" class="col-form-label">Type:
                    <select class="form-select">
                        <option value="first">Cat</option>
                        <option value="second">Dog</option>
                        <option value="third">Mouse</option>
                    </select></label>
                </div>
                <div class="form-group">
                    <label for="age">Day of Birth:</label>
                    <input type="date" class="form-control" name="age" placeholder=""
                           id="age"/>
                </div>

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
            <!-- End Form for Adding Pet -->
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

petstagram/petstagram/main/templates/pet_create.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Add Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="container mb-5" action="{% url 'create pet' %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

petstagram/petstagram/main/templates/pet_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Delete Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'delete pet' pet.pk %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-danger mt-2" type="submit">Delete</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

petstagram/petstagram/main/templates/pet_edit.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Edit Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit pet' pet.pk %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

petstagram/petstagram/main/templates/photo_create-old.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <!-- Form for Adding Photos -->
            <form method="post" action="dashboard.html">
                <div class="custom-file">
                    <label for="file-upload">Pet Image</label>
                    <input type="file" id="file-upload" class="form-control-file" name="filename">
                </div>
                <div class="form-group">
                    <label for="first_name">Description</label>
                    <textarea class="form-control" name="first_name" placeholder="Enter Description"
                              id="first_name" rows="3"></textarea>
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="checkbox">
                    <label class="custom-control-label" for="checkbox">Tom</label><br>
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="second-checkbox">
                    <label class="custom-control-label" for="second-checkbox">Jerry</label>
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="third-checkbox">
                    <label class="custom-control-label" for="third-checkbox">Spike</label>
                </div>

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
            <!-- End Form for Adding Photos -->

        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

petstagram/petstagram/main/templates/photo_create.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Add a New Pet Photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="dashboard.html">

                <!-- Form for Adding Photos -->

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

petstagram/petstagram/main/templates/photo_details.html
{% extends 'base.html' %}
{% block content %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <!-- Image -->
            <img src="{{ pet_photo.photo }}"
                 class="w-100 rounded mx-auto d-block" alt="{{ pet_photo.description }}">
        </div>
        <div class="d-inline p-2 w-50">
            <!-- Info for First Pet -->
            {% for pet in pet_photo.tagged_animals.all %}
                <div class="d-flex justify-content-around">
                    <h5><u>Type:</u> {{ pet.type }}</h5>
                    <h5><u>Name:</u> {{ pet.name }}</h5>
                    {% if pet.date_of_birth %}
                        <h5><u>Age:</u>{{ pet.age }}</h5>
                    {% endif %}
                </div>
            {% endfor %}
            <!-- Description -->
            {% if pet_photo.description %}
            <p class="mt-2">Description: {{ pet_photo.description }}</p>
            {% endif %}
            <!-- Likes Button -->
            <a href="{% url 'like photo' pet_photo.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
            <!-- Likes Counter -->
            <p class="mt-2">Likes: {{ pet_photo.likes }}</p>
            <!-- Buttons -->
            <a href="#" class="btn btn-primary">Edit</a>
            <a href="#" class="btn btn-danger">Delete</a>
        </div>
    </div>
{% endblock %}

petstagram/petstagram/main/templates/profile_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index-page' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile-page' %}">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <h1 class="text-center">Create Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form>
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" name="first_name" maxlength="30" required
                           placeholder="Enter first name" id="first_name"/>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    <input type="text" class="form-control" name="last_name" maxlength="30" required
                           placeholder="Enter last name" id="id_last_name"/>
                </div>
                <div class="form-group">
                    <label for="id_image">Link to Profile Image</label>
                    <input type="url" class="form-control" name="profile_image" required id="id_image"
                    placeholder="Enter URL"/>
                </div>
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</html>

petstagram/petstagram/main/templates/profile_create.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Create Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'create profile' %}">
                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

petstagram/petstagram/main/templates/profile_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete your profile?</h1>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post" action="{% url 'delete profile' %}">

                        {% csrf_token %}
                        {{ form }}

                        <input type="submit" value="Confirm" class="btn btn-danger"/>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}